Emulator
Ramaz-Upper-School/RamLife pull request #116
Opened 2022-01-09 03:22 UTC by todesj

2022-01-09 04:10 UTC, BraydenKO approved these changes
Lgtm

2022-01-11 05:42 UTC, Levi-Lesches approved these changes
LGTM

2022-01-11 05:48 UTC, Levi-Lesches requested changes
Sorry, missed this one change. The analyzer complained about it too

2022-01-11 05:48 UTC, Levi-Lesches commented on lib/src/services/firebase_core.dart
> +	static bool shouldUseEmulator = false;
```suggestion
	/// Whether the Firebase Local Emulator Suite should be used. 
	///
	/// This setting should be enabled during development ONLY. We can also use 
	/// `kDebugMode` from `flutter/foundation`, but it's also valid to test UI 
	/// or logic operations with the production database.
	static bool shouldUseEmulator = false;
	
```

2022-01-11 05:49 UTC, Levi-Lesches approved these changes

2022-01-11 05:53 UTC, merged